import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import PodcastList from '@/components/Podcast/List/podcast-list'
import { getPodcasts } from '@/helpers/api-util'

const inter = Inter({ subsets: ['latin'] })

export default function Home(props) {
  console.log('featuredPodcasts from props ================', props.feed);

  const { author, entry, icon, id, link, rights, title, updated } = props.feed;
  return (
    <>
      <Head>
        <title>Podcaster</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={icon.label} />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <Link href="/">
            Podcaster
          </Link>
        </div>

        <div className={styles.center}>
          {/* <PodcastList podcastList={entry} /> */}
        </div> 

        <div>
          <PodcastList podcastList={entry} />
        </div>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const featuredPodcasts = await getPodcasts();
  return {
    props: {
      feed: featuredPodcasts.feed,
    },
  };
}
