import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import PodcastList from '@/components/Podcast/List/podcast-list'
import { getPodcasts } from '@/helpers/api-util'
import PodcastSearchBar from '../components/Layout/SearchBar/podcastSearchBar'
import { useState, useEffect } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home(props) {
  const [searchValue, setSearchValue] = useState();
  const [podcasts, setPodcasts] = useState(props.feed);
  const [icon, setIcon] = useState(props.feed.icon)
  const { author, entry, id, link, rights, title, updated } = podcasts;
  const [entries, setEntries] = useState(entry);

  const searchValueHandler = async (value) => {
    setSearchValue(value)
  }

  useEffect(() => {
    if (!searchValue) {
      setEntries(entry);
      return;
    }
    else {
      const filteredEntries = entry.filter((podcastEntry) => {
        const title = podcastEntry.title.label;
        console.log(podcastEntry);
        return title.toLowerCase().includes(searchValue.toLowerCase());
      });

      setEntries(filteredEntries);
    }
  }, [searchValue, entry]);

  if (!podcasts) {
    <p>Loading...</p>
  }

  return (
    <>
      <Head>
        <title>Podcaster</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={icon.label} />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <div className={styles.center}>
            <PodcastSearchBar handleSearchChange={searchValueHandler} searchValue={searchValue} />
          </div>
        </div>
        {!entries.length && <div> <p>No results for the search</p></div>}
        <div>
          {entries && <PodcastList podcastList={entries} />}
        </div>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const featuredPodcasts = await getPodcasts();
  return {
    props: {
      feed: featuredPodcasts.feed,
    },
  };
}
